/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.app_reserva_vuelos.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author Bogard Axel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
        private void toggleFechaRegreso() {
        String tipoViaje = (String) cmbtipo.getSelectedItem();
        if ("Ida y vuelta".equals(tipoViaje)) {
            dateregreso.setEnabled(true);
            lblRegreso.setForeground(new Color(100, 100, 100));
        } else {
            dateregreso.setEnabled(false);
            dateregreso.setDate(null);
            lblRegreso.setForeground(new Color(200, 200, 200));
        }
    }
        
       
        private void buscarVuelos() {
        // Validaciones
        String origen = (String) cmbOrigen.getSelectedItem();
        String destino = (String) cmbDestino.getSelectedItem();
        Date fechaSalida = datesalida.getDate();

        if (origen.equals(destino)) {
            JOptionPane.showMessageDialog(this, 
            "El origen y destino no pueden ser iguales", 
            "Error de validación", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
        
        // Aquí iría la lógica para buscar vuelos en la base de datos
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String mensaje = String.format(
            "Buscando vuelos:\n\n" +
            "De: %s\n" +
            "A: %s\n" +
            "Salida: %s\n" +
            "Pasajeros: %d\n" +
            "Tipo: %s",
            origen, destino, sdf.format(fechaSalida),
            cmbpasajeros.getSelectedItem(),
            cmbtipo.getSelectedItem()
        );
        
        JOptionPane.showMessageDialog(this, 
            mensaje, 
            "Búsqueda de vuelos", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Aquí puedes abrir una nueva ventana con los resultados
        // VentanaResultados ventanaResultados = new VentanaResultados(datos);
        // ventanaResultados.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panprincipal = new javax.swing.JPanel();
        panbusqueda = new javax.swing.JPanel();
        cmbtipo = new javax.swing.JComboBox<>();
        cmbpasajeros = new javax.swing.JComboBox<>();
        datesalida = new com.toedter.calendar.JDateChooser();
        dateregreso = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        lblRegreso = new javax.swing.JLabel();
        lblOrigen1 = new javax.swing.JLabel();
        lblOrigen2 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panbusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ida y Vuelta", "Viaje Sencillo" }));
        cmbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoActionPerformed(evt);
            }
        });

        cmbpasajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btnBuscar.setText("Buscar Vuelos");

        lblOrigen.setText("Origen");

        lblDestino.setText("Destino");

        lblSalida.setText("Salida");

        lblRegreso.setText("Regreso");

        lblOrigen1.setText("Tipo de Viaje");

        lblOrigen2.setText("Pasajeros");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad de México (MEX)", "Guadalajara (GDL)", "Monterrey (MTY)", "Cancún (CUN)", "Tijuana (TIJ)", "Los Cabos (SJD)", "Puerto Vallarta (PVR)", "Mérida (MID)" }));

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad de México (MEX)", "Guadalajara (GDL)", "Monterrey (MTY)", "Cancún (CUN)", "Tijuana (TIJ)", "Los Cabos (SJD)", "Puerto Vallarta (PVR)", "Mérida (MID)", " " }));

        javax.swing.GroupLayout panbusquedaLayout = new javax.swing.GroupLayout(panbusqueda);
        panbusqueda.setLayout(panbusquedaLayout);
        panbusquedaLayout.setHorizontalGroup(
            panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(32, 32, 32))
            .addGroup(panbusquedaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigen1)
                    .addComponent(cmbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbpasajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDestino)
                    .addComponent(lblOrigen2)
                    .addComponent(cmbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegreso)
                    .addComponent(datesalida, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(dateregreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panbusquedaLayout.setVerticalGroup(
            panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbusquedaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalida)
                    .addComponent(lblOrigen1)
                    .addComponent(lblOrigen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datesalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbpasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panbusquedaLayout.createSequentialGroup()
                        .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrigen)
                            .addComponent(lblDestino))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbusquedaLayout.createSequentialGroup()
                        .addComponent(lblRegreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(dateregreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(16, 16, 16))
        );

        lblTitulo.setText("TUP Vuelos");

        lblSubtitulo.setText("Hola");

        javax.swing.GroupLayout panprincipalLayout = new javax.swing.GroupLayout(panprincipal);
        panprincipal.setLayout(panprincipalLayout);
        panprincipalLayout.setHorizontalGroup(
            panprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panprincipalLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(panprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo)
                    .addComponent(panbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panprincipalLayout.setVerticalGroup(
            panprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panprincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(18, 18, 18)
                .addComponent(panbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbpasajeros;
    private javax.swing.JComboBox<String> cmbtipo;
    private com.toedter.calendar.JDateChooser dateregreso;
    private com.toedter.calendar.JDateChooser datesalida;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblOrigen1;
    private javax.swing.JLabel lblOrigen2;
    private javax.swing.JLabel lblRegreso;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panbusqueda;
    private javax.swing.JPanel panprincipal;
    // End of variables declaration//GEN-END:variables
}