/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.app_reserva_vuelos.gui;

/**
 *
 * @author Bogard Axel
 */
public class hola extends javax.swing.JInternalFrame {

    /**
     * Creates new form hola
     */
    public hola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panbusqueda = new javax.swing.JPanel();
        cmbtipo = new javax.swing.JComboBox<>();
        cmbpasajeros = new javax.swing.JComboBox<>();
        datesalida = new com.toedter.calendar.JDateChooser();
        dateregreso = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        lblRegreso = new javax.swing.JLabel();
        lblOrigen1 = new javax.swing.JLabel();
        lblOrigen2 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();

        panbusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ida y Vuelta", "Viaje Sencillo" }));
        cmbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoActionPerformed(evt);
            }
        });

        cmbpasajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btnBuscar.setText("Buscar Vuelos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblOrigen.setText("Origen");

        lblDestino.setText("Destino");

        lblSalida.setText("Salida");

        lblRegreso.setText("Regreso");

        lblOrigen1.setText("Tipo de Viaje");

        lblOrigen2.setText("Pasajeros");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUN - Aeropuerto Internacional de Cancún", "YYZ - Aeropuerto Internacional Toronto Pearson", "GIG - Aeropuerto Internacional de Galeão", "SCL - Aeropuerto Internacional Arturo Merino Benítez", "MAD - Aeropuerto Adolfo Suárez Madrid-Barajas", "CDG - Aeropuerto de París-Charles de Gaulle", "BER - Aeropuerto de Berlín Brandeburgo", "FCO - Aeropuerto de Roma-Fiumicino", "NRT - Aeropuerto Internacional de Narita", "PEK - Aeropuerto Internacional de Pekín Capital", "SYD - Aeropuerto de Sídney", "CPT - Aeropuerto Internacional de Ciudad del Cabo", "DEL - Aeropuerto Internacional Indira Gandhi", "CAI - Aeropuerto Internacional de El Cairo", "DXB - Aeropuerto Internacional de Dubái" }));
        cmbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigenActionPerformed(evt);
            }
        });

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUN - Aeropuerto Internacional de Cancún", "YYZ - Aeropuerto Internacional Toronto Pearson", "GIG - Aeropuerto Internacional de Galeão", "SCL - Aeropuerto Internacional Arturo Merino Benítez", "MAD - Aeropuerto Adolfo Suárez Madrid-Barajas", "CDG - Aeropuerto de París-Charles de Gaulle", "BER - Aeropuerto de Berlín Brandeburgo", "FCO - Aeropuerto de Roma-Fiumicino", "NRT - Aeropuerto Internacional de Narita", "PEK - Aeropuerto Internacional de Pekín Capital", "SYD - Aeropuerto de Sídney", "CPT - Aeropuerto Internacional de Ciudad del Cabo", "DEL - Aeropuerto Internacional Indira Gandhi", "CAI - Aeropuerto Internacional de El Cairo", "DXB - Aeropuerto Internacional de Dubái" }));

        javax.swing.GroupLayout panbusquedaLayout = new javax.swing.GroupLayout(panbusqueda);
        panbusqueda.setLayout(panbusquedaLayout);
        panbusquedaLayout.setHorizontalGroup(
            panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(32, 32, 32))
            .addGroup(panbusquedaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigen1)
                    .addComponent(cmbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbpasajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDestino)
                    .addComponent(lblOrigen2)
                    .addComponent(cmbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegreso)
                    .addComponent(datesalida, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(dateregreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panbusquedaLayout.setVerticalGroup(
            panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbusquedaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalida)
                    .addComponent(lblOrigen1)
                    .addComponent(lblOrigen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datesalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbpasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panbusquedaLayout.createSequentialGroup()
                        .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrigen)
                            .addComponent(lblDestino))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbusquedaLayout.createSequentialGroup()
                        .addComponent(lblRegreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(dateregreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(panbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbpasajeros;
    private javax.swing.JComboBox<String> cmbtipo;
    private com.toedter.calendar.JDateChooser dateregreso;
    private com.toedter.calendar.JDateChooser datesalida;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblOrigen1;
    private javax.swing.JLabel lblOrigen2;
    private javax.swing.JLabel lblRegreso;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JPanel panbusqueda;
    // End of variables declaration//GEN-END:variables
}
