/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.app_reserva_vuelos.gui;

/**
 *
 * @author Bogard Axel
 */
public class PanelBuscar extends javax.swing.JPanel {

    /**
     * Creates new form PanelReservas
     */
    public PanelBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        btnrealizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnlmpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblorigen = new javax.swing.JLabel();
        lbldestino = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblsalida = new javax.swing.JLabel();
        lblregreso = new javax.swing.JLabel();
        lblpasajeros = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        spinpasajeros = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        cmbOrigen1 = new javax.swing.JComboBox<>();
        cmbOrigen2 = new javax.swing.JComboBox<>();

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnrealizar.setText("Realizar reserva");
        jPanel4.add(btnrealizar);

        btncancelar.setText("Cancelar reserva");
        jPanel4.add(btncancelar);

        btnlmpiar.setText("Limpiar");
        jPanel4.add(btnlmpiar);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reserva."));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblorigen.setText("Tipo de Viaje:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblorigen, gridBagConstraints);

        lbldestino.setText("Salida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lbldestino, gridBagConstraints);

        lblnombre.setText("Regreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblnombre, gridBagConstraints);

        lblsalida.setText("Origen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblsalida, gridBagConstraints);

        lblregreso.setText("Destino:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblregreso, gridBagConstraints);

        lblpasajeros.setText("Pasajeros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblpasajeros, gridBagConstraints);

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ida y Vuelta", "Sencillo" }));
        cmbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(cmbOrigen, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(spinpasajeros, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jDateChooser1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jDateChooser2, gridBagConstraints);

        cmbOrigen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUN - Aeropuerto de Cancún", "YYZ - Aeropuerto Toronto Pearson", "GIG - Aeropuerto de Galeão", "SCL - Aeropuerto Arturo Merino Benítez", "MAD - Aeropuerto Adolfo Suárez Madrid-Barajas", "CDG - Aeropuerto de París-Charles de Gaulle", "BER - Aeropuerto de Berlín Brandeburgo", "FCO - Aeropuerto de Roma-Fiumicino", "NRT - Aeropuerto de Narita", "PEK - Aeropuerto de Pekín Capital", "SYD - Aeropuerto de Sídney", "CPT - Aeropuerto de Ciudad del Cabo", "DEL - Aeropuerto Indira Gandhi", "CAI - Aeropuerto de El Cairo", "DXB - Aeropuerto de Dubái" }));
        cmbOrigen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigen1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(cmbOrigen1, gridBagConstraints);

        cmbOrigen2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUN - Aeropuerto de Cancún", "YYZ - Aeropuerto Toronto Pearson", "GIG - Aeropuerto de Galeão", "SCL - Aeropuerto Arturo Merino Benítez", "MAD - Aeropuerto Adolfo Suárez Madrid-Barajas", "CDG - Aeropuerto de París-Charles de Gaulle", "BER - Aeropuerto de Berlín Brandeburgo", "FCO - Aeropuerto de Roma-Fiumicino", "NRT - Aeropuerto de Narita", "PEK - Aeropuerto de Pekín Capital", "SYD - Aeropuerto de Sídney", "CPT - Aeropuerto de Ciudad del Cabo", "DEL - Aeropuerto Indira Gandhi", "CAI - Aeropuerto de El Cairo", "DXB - Aeropuerto de Dubái", " " }));
        cmbOrigen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigen2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(cmbOrigen2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigenActionPerformed

    private void cmbOrigen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigen1ActionPerformed

    private void cmbOrigen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigen2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnlmpiar;
    private javax.swing.JButton btnrealizar;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbOrigen1;
    private javax.swing.JComboBox<String> cmbOrigen2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbldestino;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblorigen;
    private javax.swing.JLabel lblpasajeros;
    private javax.swing.JLabel lblregreso;
    private javax.swing.JLabel lblsalida;
    private javax.swing.JSpinner spinpasajeros;
    // End of variables declaration//GEN-END:variables
}
