/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.app_reserva_vuelos.gui;

import com.mycompany.app_reserva_vuelos.model.*;
import com.mycompany.app_reserva_vuelos.service.*;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bogard Axel
 */
public class PanelBuscar extends javax.swing.JPanel {

    private ReservaService reservaService;
    private VueloService vueloService;
    private PasajeroService pasajeroService;
    private UsuarioService usuarioService;
    private AeropuertoService aeropuertoService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form PanelBuscar
     */
    public PanelBuscar() {
        initComponents();
        this.reservaService = new ReservaServiceImpl();
        this.vueloService = new VueloServiceImpl();
        this.pasajeroService = new PasajeroServiceImpl();
        this.usuarioService = UsuarioServiceImpl.getInstance();
        this.aeropuertoService = new AeropuertoServiceImpl();
        inicializarTabla();
        configurarMensajeBienvenida();
        cargarReservasUsuario();
    }

    private void inicializarTabla() {
        String[] columnNames = { "Código Reserva", "Fecha", "Estado", "Origen", "Destino", "Vuelo" };
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
    }

    private void configurarMensajeBienvenida() {
        Usuario usuarioActual = usuarioService.getUsuarioAutenticado();
        if (usuarioActual != null) {
            lblBienvenida.setText("Bienvenido " + usuarioActual.getNombre() + ", aquí encontrarás tus reservas");
        } else {
            lblBienvenida.setText("Bienvenido, aquí encontrarás tus reservas");
        }
    }

    private void cargarReservasUsuario() {
        tableModel.setRowCount(0);

        Usuario usuarioActual = usuarioService.getUsuarioAutenticado();
        if (usuarioActual == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe iniciar sesión para ver sus reservas.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Pasajero pasajero = pasajeroService.obtenerPasajeroPorEmail(usuarioActual.getEmail());
        if (pasajero == null) {
            lblBienvenida.setText("Bienvenido " + usuarioActual.getNombre() + ", aún no tienes reservas");
            return;
        }

        List<Reserva> reservas = reservaService.listarReservasPorPasajero(pasajero.getIdPasajero());
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Reserva reserva : reservas) {
            List<DetalleReserva> detalles = reservaService.obtenerDetallesPorReserva(reserva.getIdReserva());

            for (DetalleReserva detalle : detalles) {
                Vuelo vuelo = vueloService.obtenerVueloPorId(detalle.getIdVuelo());

                if (vuelo != null) {
                    Aeropuerto origen = aeropuertoService.obtenerPorId(vuelo.getIdAeropuertoOrigen());
                    Aeropuerto destino = aeropuertoService.obtenerPorId(vuelo.getIdAeropuertoDestino());

                    String origenStr = origen != null ? origen.getCodigoIATA() : "N/A";
                    String destinoStr = destino != null ? destino.getCodigoIATA() : "N/A";
                    String fechaStr = reserva.getFechaReserva() != null
                            ? reserva.getFechaReserva().format(dateFormatter)
                            : "N/A";

                    tableModel.addRow(new Object[] {
                            reserva.getCodigoReserva(),
                            fechaStr,
                            reserva.getEstadoReserva(),
                            origenStr,
                            destinoStr,
                            vuelo.getNumeroVuelo()
                    });
                }
            }
        }

        if (reservas.isEmpty()) {
            lblBienvenida.setText("Bienvenido " + usuarioActual.getNombre() + ", aún no tienes reservas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido, aquí encontrarás tus reservas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Código Reserva", "Fecha", "Estado", "Origen", "Destino", "Vuelo"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnActualizar.setText("Actualizar Reservas");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788,
                                                Short.MAX_VALUE)
                                        .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnActualizar)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(25, 25, 25)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        cargarReservasUsuario();
        JOptionPane.showMessageDialog(this, "Reservas actualizadas", "Información", JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
